#############################################################################
# Makefile for building: VVR12
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  VVR12.pro
# Template: app
# Command: /work/buildroot/output-buildroot-2017.02.5/host/usr/bin/qmake -o Makefile VVR12.pro -spec devices/linux-buildroot-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /work/buildroot/output-buildroot-2017.02.5/host/usr/bin/arm-buildroot-linux-gnueabihf-gcc
CXX           = /work/buildroot/output-buildroot-2017.02.5/host/usr/bin/arm-buildroot-linux-gnueabihf-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os --sysroot=/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os --sysroot=/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot -O2 -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I. -I. -I/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++
QMAKE         = /work/buildroot/output-buildroot-2017.02.5/host/usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = VVR121.0.0
DISTDIR = /home/ubuntu/VRFW/VRFW_Modify_200102/VRFW_Modifyv8_Safety_v3_Footswitch/VRFW/.tmp/VVR121.0.0
LINK          = /work/buildroot/output-buildroot-2017.02.5/host/usr/bin/arm-buildroot-linux-gnueabihf-g++
LFLAGS        = --sysroot=/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Core -lrt -ldl -latomic -lpthread 
AR            = /work/buildroot/output-buildroot-2017.02.5/host/usr/bin/arm-buildroot-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /work/buildroot/output-buildroot-2017.02.5/host/usr/bin/arm-buildroot-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainsystem.cpp \
		workerthread.cpp \
		sysparm.cpp \
		rfoutputmodes.cpp \
		outputthread.cpp \
		outputmode.cpp \
		monitoringtask.cpp \
		gpiotools.cpp \
		mrfa_rf_table.c \
		setting.cpp \
		sysmessage.cpp \
		initializing.cpp \
		qgaugedrawfuncions.cpp \
		qgauge.cpp \
		calibration.cpp \
		gpiobutton.cpp qrc_fonts.cpp \
		qrc_image.cpp \
		moc_mainsystem.cpp \
		moc_outputthread.cpp \
		moc_monitoringtask.cpp \
		moc_setting.cpp \
		moc_sysmessage.cpp \
		moc_initializing.cpp \
		moc_qgauge.cpp \
		moc_calibration.cpp \
		moc_gpiobutton.cpp
OBJECTS       = main.o \
		mainsystem.o \
		workerthread.o \
		sysparm.o \
		rfoutputmodes.o \
		outputthread.o \
		outputmode.o \
		monitoringtask.o \
		gpiotools.o \
		mrfa_rf_table.o \
		setting.o \
		sysmessage.o \
		initializing.o \
		qgaugedrawfuncions.o \
		qgauge.o \
		calibration.o \
		gpiobutton.o \
		qrc_fonts.o \
		qrc_image.o \
		moc_mainsystem.o \
		moc_outputthread.o \
		moc_monitoringtask.o \
		moc_setting.o \
		moc_sysmessage.o \
		moc_initializing.o \
		moc_qgauge.o \
		moc_calibration.o \
		moc_gpiobutton.o
DIST          = /work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/spec_pre.prf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/unix.conf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/linux.conf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/sanitize.conf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/gcc-base.conf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/gcc-base-unix.conf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/g++-base.conf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/g++-unix.conf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/qdevice.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/device_config.prf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/common/linux_device_pre.conf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++/arch.conf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/common/linux_device_post.conf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/qconfig.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_concurrent.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_concurrent_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_core.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_core_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_fb_support_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_gui.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_gui_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_input_support_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_multimedia.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_multimedia_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_network.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_network_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_printsupport.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_printsupport_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_service_support_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_sql.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_sql_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_testlib.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_testlib_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_theme_support_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_widgets.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_widgets_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_xml.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_xml_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_zlib_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/qt_functions.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/qt_config.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++/qmake.conf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/spec_post.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/exclusive_builds.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/toolchain.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/default_pre.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/resolve_config.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/default_post.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/warn_on.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/qt.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/resources.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/moc.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/uic.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/unix/thread.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/qmake_use.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/file_copies.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/testcase_targets.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/exceptions.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/yacc.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/lex.prf \
		VVR12.pro mainsystem.h \
		workerthread.h \
		sysparm.h \
		rfoutputmodes.h \
		outputthread.h \
		outputmode.h \
		mrfa_rf_table.h \
		monitoringtask.h \
		include.h \
		gpiotools.h \
		global.h \
		setting.h \
		sysmessage.h \
		initializing.h \
		QGauge/qgauge.h \
		calibration.h \
		gpiobutton.h main.cpp \
		mainsystem.cpp \
		workerthread.cpp \
		sysparm.cpp \
		rfoutputmodes.cpp \
		outputthread.cpp \
		outputmode.cpp \
		monitoringtask.cpp \
		gpiotools.cpp \
		mrfa_rf_table.c \
		setting.cpp \
		sysmessage.cpp \
		initializing.cpp \
		qgaugedrawfuncions.cpp \
		qgauge.cpp \
		calibration.cpp \
		gpiobutton.cpp
QMAKE_TARGET  = VVR12
DESTDIR       = 
TARGET        = VVR12


first: all
####### Build rules

$(TARGET): ui_mainsystem.h ui_setting.h ui_sysmessage.h ui_initializing.h ui_calibration.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: VVR12.pro /work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++/qmake.conf /work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/spec_pre.prf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/unix.conf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/linux.conf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/sanitize.conf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/gcc-base.conf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/gcc-base-unix.conf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/g++-base.conf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/g++-unix.conf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/qdevice.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/device_config.prf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/common/linux_device_pre.conf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++/arch.conf \
		../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/common/linux_device_post.conf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/qconfig.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_concurrent.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_concurrent_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_core.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_core_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_fb_support_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_gui.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_gui_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_input_support_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_multimedia.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_multimedia_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_network.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_network_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_printsupport.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_printsupport_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_service_support_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_sql.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_sql_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_testlib.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_testlib_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_theme_support_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_widgets.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_widgets_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_xml.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_xml_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_zlib_private.pri \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/qt_functions.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/qt_config.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++/qmake.conf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/spec_post.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/exclusive_builds.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/toolchain.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/default_pre.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/resolve_config.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/default_post.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/warn_on.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/qt.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/resources.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/moc.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/uic.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/unix/thread.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/qmake_use.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/file_copies.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/testcase_targets.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/exceptions.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/yacc.prf \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/lex.prf \
		VVR12.pro \
		fonts.qrc \
		image.qrc \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Widgets.prl \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Gui.prl \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Core.prl
	$(QMAKE) -o Makefile VVR12.pro -spec devices/linux-buildroot-g++
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/spec_pre.prf:
../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/unix.conf:
../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/linux.conf:
../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/sanitize.conf:
../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/gcc-base.conf:
../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/gcc-base-unix.conf:
../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/g++-base.conf:
../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/common/g++-unix.conf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/qdevice.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/device_config.prf:
../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/common/linux_device_pre.conf:
../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++/arch.conf:
../../../../starmed/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/common/linux_device_post.conf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/qconfig.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_bootstrap_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_concurrent.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_concurrent_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_core.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_core_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_fb_support_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_gui.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_gui_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_input_support_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_multimedia.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_multimedia_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_multimediawidgets.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_network.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_network_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_printsupport.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_printsupport_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_service_support_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_sql.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_sql_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_testlib.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_testlib_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_theme_support_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_widgets.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_widgets_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_xml.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_xml_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/modules/qt_lib_zlib_private.pri:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/qt_functions.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/qt_config.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++/qmake.conf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/spec_post.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/exclusive_builds.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/toolchain.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/default_pre.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/resolve_config.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/default_post.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/warn_on.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/qt.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/resources.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/moc.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/uic.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/unix/thread.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/qmake_use.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/file_copies.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/testcase_targets.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/exceptions.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/yacc.prf:
/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/lex.prf:
VVR12.pro:
fonts.qrc:
image.qrc:
/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Widgets.prl:
/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Gui.prl:
/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile VVR12.pro -spec devices/linux-buildroot-g++

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents fonts.qrc image.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainsystem.h workerthread.h sysparm.h rfoutputmodes.h outputthread.h outputmode.h mrfa_rf_table.h monitoringtask.h include.h gpiotools.h global.h setting.h sysmessage.h initializing.h QGauge/qgauge.h calibration.h gpiobutton.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainsystem.cpp workerthread.cpp sysparm.cpp rfoutputmodes.cpp outputthread.cpp outputmode.cpp monitoringtask.cpp gpiotools.cpp mrfa_rf_table.c setting.cpp sysmessage.cpp initializing.cpp qgaugedrawfuncions.cpp qgauge.cpp calibration.cpp gpiobutton.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainsystem.ui setting.ui sysmessage.ui initializing.ui calibration.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_fonts.cpp qrc_image.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_fonts.cpp qrc_image.cpp
qrc_fonts.cpp: fonts.qrc \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/rcc \
		starmedfont.ttf
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/rcc -name fonts fonts.qrc -o qrc_fonts.cpp

qrc_image.cpp: image.qrc \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/rcc \
		watt.png \
		stop.png \
		serialno.png \
		temp.png \
		start.png \
		time.png \
		action.png \
		danger.png
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/rcc -name image image.qrc -o qrc_image.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/data/dummy.cpp
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/arm-buildroot-linux-gnueabihf-g++ -pipe -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os --sysroot=/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot -O2 -O3 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainsystem.cpp moc_outputthread.cpp moc_monitoringtask.cpp moc_setting.cpp moc_sysmessage.cpp moc_initializing.cpp moc_qgauge.cpp moc_calibration.cpp moc_gpiobutton.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainsystem.cpp moc_outputthread.cpp moc_monitoringtask.cpp moc_setting.cpp moc_sysmessage.cpp moc_initializing.cpp moc_qgauge.cpp moc_calibration.cpp moc_gpiobutton.cpp
moc_mainsystem.cpp: global.h \
		include.h \
		sysparm.h \
		outputmode.h \
		setting.h \
		calibration.h \
		gpiotools.h \
		mrfa_rf_table.h \
		sysmessage.h \
		initializing.h \
		mainsystem.h \
		moc_predefs.h \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++ -I/home/ubuntu/VRFW/VRFW_Modify_200102/VRFW_Modifyv8_Safety_v3_Footswitch/VRFW -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0 -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/arm-buildroot-linux-gnueabihf -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/backward -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include-fixed -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include mainsystem.h -o moc_mainsystem.cpp

moc_outputthread.cpp: workerthread.h \
		outputmode.h \
		sysparm.h \
		global.h \
		include.h \
		monitoringtask.h \
		outputthread.h \
		moc_predefs.h \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++ -I/home/ubuntu/VRFW/VRFW_Modify_200102/VRFW_Modifyv8_Safety_v3_Footswitch/VRFW -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0 -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/arm-buildroot-linux-gnueabihf -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/backward -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include-fixed -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include outputthread.h -o moc_outputthread.cpp

moc_monitoringtask.cpp: sysparm.h \
		global.h \
		include.h \
		monitoringtask.h \
		moc_predefs.h \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++ -I/home/ubuntu/VRFW/VRFW_Modify_200102/VRFW_Modifyv8_Safety_v3_Footswitch/VRFW -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0 -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/arm-buildroot-linux-gnueabihf -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/backward -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include-fixed -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include monitoringtask.h -o moc_monitoringtask.cpp

moc_setting.cpp: sysparm.h \
		global.h \
		include.h \
		calibration.h \
		gpiotools.h \
		mrfa_rf_table.h \
		sysmessage.h \
		setting.h \
		moc_predefs.h \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++ -I/home/ubuntu/VRFW/VRFW_Modify_200102/VRFW_Modifyv8_Safety_v3_Footswitch/VRFW -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0 -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/arm-buildroot-linux-gnueabihf -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/backward -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include-fixed -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include setting.h -o moc_setting.cpp

moc_sysmessage.cpp: sysmessage.h \
		moc_predefs.h \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++ -I/home/ubuntu/VRFW/VRFW_Modify_200102/VRFW_Modifyv8_Safety_v3_Footswitch/VRFW -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0 -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/arm-buildroot-linux-gnueabihf -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/backward -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include-fixed -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include sysmessage.h -o moc_sysmessage.cpp

moc_initializing.cpp: global.h \
		include.h \
		mrfa_rf_table.h \
		initializing.h \
		moc_predefs.h \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++ -I/home/ubuntu/VRFW/VRFW_Modify_200102/VRFW_Modifyv8_Safety_v3_Footswitch/VRFW -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0 -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/arm-buildroot-linux-gnueabihf -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/backward -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include-fixed -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include initializing.h -o moc_initializing.cpp

moc_qgauge.cpp: QGauge/qgauge.h \
		moc_predefs.h \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++ -I/home/ubuntu/VRFW/VRFW_Modify_200102/VRFW_Modifyv8_Safety_v3_Footswitch/VRFW -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0 -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/arm-buildroot-linux-gnueabihf -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/backward -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include-fixed -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include QGauge/qgauge.h -o moc_qgauge.cpp

moc_calibration.cpp: global.h \
		include.h \
		gpiotools.h \
		sysparm.h \
		mrfa_rf_table.h \
		calibration.h \
		moc_predefs.h \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++ -I/home/ubuntu/VRFW/VRFW_Modify_200102/VRFW_Modifyv8_Safety_v3_Footswitch/VRFW -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0 -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/arm-buildroot-linux-gnueabihf -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/backward -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include-fixed -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include calibration.h -o moc_calibration.cpp

moc_gpiobutton.cpp: gpiotools.h \
		global.h \
		include.h \
		gpiobutton.h \
		moc_predefs.h \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/work/buildroot/output-buildroot-2017.02.5/host/usr/mkspecs/devices/linux-buildroot-g++ -I/home/ubuntu/VRFW/VRFW_Modify_200102/VRFW_Modifyv8_Safety_v3_Footswitch/VRFW -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0 -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/arm-buildroot-linux-gnueabihf -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include/c++/5.4.0/backward -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include -I/opt/toolchain/imx6s/starmed/usr/lib/gcc/arm-buildroot-linux-gnueabihf/5.4.0/include-fixed -I/opt/toolchain/imx6s/starmed/usr/arm-buildroot-linux-gnueabihf/include -I/work/buildroot/output-buildroot-2017.02.5/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include gpiobutton.h -o moc_gpiobutton.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainsystem.h ui_setting.h ui_sysmessage.h ui_initializing.h ui_calibration.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainsystem.h ui_setting.h ui_sysmessage.h ui_initializing.h ui_calibration.h
ui_mainsystem.h: mainsystem.ui \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/uic \
		QGauge/qgauge.h
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/uic mainsystem.ui -o ui_mainsystem.h

ui_setting.h: setting.ui \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/uic
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/uic setting.ui -o ui_setting.h

ui_sysmessage.h: sysmessage.ui \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/uic
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/uic sysmessage.ui -o ui_sysmessage.h

ui_initializing.h: initializing.ui \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/uic
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/uic initializing.ui -o ui_initializing.h

ui_calibration.h: calibration.ui \
		/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/uic
	/work/buildroot/output-buildroot-2017.02.5/host/usr/bin/uic calibration.ui -o ui_calibration.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp global.h \
		include.h \
		gpiotools.h \
		mainsystem.h \
		sysparm.h \
		outputmode.h \
		setting.h \
		calibration.h \
		mrfa_rf_table.h \
		sysmessage.h \
		initializing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainsystem.o: mainsystem.cpp ui_mainsystem.h \
		mainsystem.h \
		global.h \
		include.h \
		sysparm.h \
		outputmode.h \
		setting.h \
		calibration.h \
		gpiotools.h \
		mrfa_rf_table.h \
		sysmessage.h \
		initializing.h \
		gpiobutton.h \
		outputthread.h \
		workerthread.h \
		monitoringtask.h \
		QGauge/qgauge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainsystem.o mainsystem.cpp

workerthread.o: workerthread.cpp workerthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o workerthread.o workerthread.cpp

sysparm.o: sysparm.cpp sysparm.h \
		global.h \
		include.h \
		mrfa_rf_table.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sysparm.o sysparm.cpp

rfoutputmodes.o: rfoutputmodes.cpp rfoutputmodes.h \
		outputmode.h \
		sysparm.h \
		global.h \
		include.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rfoutputmodes.o rfoutputmodes.cpp

outputthread.o: outputthread.cpp outputthread.h \
		workerthread.h \
		outputmode.h \
		sysparm.h \
		global.h \
		include.h \
		monitoringtask.h \
		gpiotools.h \
		rfoutputmodes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o outputthread.o outputthread.cpp

outputmode.o: outputmode.cpp outputmode.h \
		sysparm.h \
		global.h \
		include.h \
		gpiotools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o outputmode.o outputmode.cpp

monitoringtask.o: monitoringtask.cpp monitoringtask.h \
		sysparm.h \
		global.h \
		include.h \
		mrfa_rf_table.h \
		gpiotools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o monitoringtask.o monitoringtask.cpp

gpiotools.o: gpiotools.cpp gpiotools.h \
		global.h \
		include.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpiotools.o gpiotools.cpp

mrfa_rf_table.o: mrfa_rf_table.c mrfa_rf_table.h \
		global.h \
		include.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o mrfa_rf_table.o mrfa_rf_table.c

setting.o: setting.cpp setting.h \
		sysparm.h \
		global.h \
		include.h \
		calibration.h \
		gpiotools.h \
		mrfa_rf_table.h \
		sysmessage.h \
		ui_setting.h \
		mainsystem.h \
		outputmode.h \
		initializing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setting.o setting.cpp

sysmessage.o: sysmessage.cpp sysmessage.h \
		ui_sysmessage.h \
		mainsystem.h \
		global.h \
		include.h \
		sysparm.h \
		outputmode.h \
		setting.h \
		calibration.h \
		gpiotools.h \
		mrfa_rf_table.h \
		initializing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sysmessage.o sysmessage.cpp

initializing.o: initializing.cpp initializing.h \
		global.h \
		include.h \
		mrfa_rf_table.h \
		ui_initializing.h \
		mainsystem.h \
		sysparm.h \
		outputmode.h \
		setting.h \
		calibration.h \
		gpiotools.h \
		sysmessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o initializing.o initializing.cpp

qgaugedrawfuncions.o: qgaugedrawfuncions.cpp QGauge/qgauge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qgaugedrawfuncions.o qgaugedrawfuncions.cpp

qgauge.o: qgauge.cpp QGauge/qgauge.h \
		mainsystem.h \
		global.h \
		include.h \
		sysparm.h \
		outputmode.h \
		setting.h \
		calibration.h \
		gpiotools.h \
		mrfa_rf_table.h \
		sysmessage.h \
		initializing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qgauge.o qgauge.cpp

calibration.o: calibration.cpp calibration.h \
		global.h \
		include.h \
		gpiotools.h \
		sysparm.h \
		mrfa_rf_table.h \
		ui_calibration.h \
		mainsystem.h \
		outputmode.h \
		setting.h \
		sysmessage.h \
		initializing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibration.o calibration.cpp

gpiobutton.o: gpiobutton.cpp gpiobutton.h \
		gpiotools.h \
		global.h \
		include.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpiobutton.o gpiobutton.cpp

qrc_fonts.o: qrc_fonts.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_fonts.o qrc_fonts.cpp

qrc_image.o: qrc_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_image.o qrc_image.cpp

moc_mainsystem.o: moc_mainsystem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainsystem.o moc_mainsystem.cpp

moc_outputthread.o: moc_outputthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_outputthread.o moc_outputthread.cpp

moc_monitoringtask.o: moc_monitoringtask.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_monitoringtask.o moc_monitoringtask.cpp

moc_setting.o: moc_setting.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setting.o moc_setting.cpp

moc_sysmessage.o: moc_sysmessage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sysmessage.o moc_sysmessage.cpp

moc_initializing.o: moc_initializing.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_initializing.o moc_initializing.cpp

moc_qgauge.o: moc_qgauge.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qgauge.o moc_qgauge.cpp

moc_calibration.o: moc_calibration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calibration.o moc_calibration.cpp

moc_gpiobutton.o: moc_gpiobutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gpiobutton.o moc_gpiobutton.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

